version: "3"

x-app: &app
  build:
    context: .
    dockerfile: docker/local/Dockerfile
  image: blog-on-rails:1.0.0
  tmpfs:
    - /app/tmp
    - /app/tmp/pids

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - ./app:/app:cached
    - rails_cache:/app/tmp/cache
    - bundle:/usr/local/bundle
  environment:
    RAILS_ENV: ${RAILS_ENV:-development}
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    XDG_DATA_HOME: /app/tmp/cache
    IRB_HISTFILE: /usr/local/hist/.irb_history
    HISTFILE: /app/log/.bash_history
    EDITOR: vi
    DB_HOST: mysql
    DB_PORT: 3306
    DB_USERNAME: ${DB_USER:-root}
    DB_PASSWORD: ${DB_PASSWORD:-password}

services:
  web:
    <<: *backend
    command: bin/dev
    ports:
      - "${RAILS_PORT:-3010}:3000"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    restart: always
    ports:
      - 3306
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      retries: 5
      start_period: 5s

volumes:
  bundle:
  mysql:
  rails_cache:
